### ISSUE TITLE
Invalid memory address or nil pointer dereference in ServiceClient

### ISSUE THREAD

**Issue by maxlinc** [rackspace/gophercloud#370]
I'm getting an error while trying to test an example based on the [Create Network documentation](http://gophercloud.io/docs/networking/#create-network). There's a good chance my code is wrong but @smashwilson took a quick look and said it looked okay at first glance.

My code:
```go
package main

import (
  "fmt"
  "os"
  "github.com/rackspace/gophercloud"
  "github.com/rackspace/gophercloud/rackspace"
  "github.com/rackspace/gophercloud/openstack/networking/v2/networks"
)

func main() {
  ao := gophercloud.AuthOptions{
    IdentityEndpoint: os.Getenv("OS_AUTH_URL"),
    Username: os.Getenv("RAX_USERNAME"),
    APIKey:   os.Getenv("RAX_API_KEY"),
  }
  provider, err := rackspace.AuthenticatedClient(ao)
  if err != nil {
    panic(err)
  }

  client, err := rackspace.NewNetworkV2(provider, gophercloud.EndpointOpts{
    Name:   "neutron",
    Region: os.Getenv("RAX_REGION"),
  })

  // We specify a name and that it should forward packets
  opts := networks.CreateOpts{Name: "main_network", AdminStateUp: networks.Up}

  // Execute the operation and get back a networks.Network struct
  network, err := networks.Create(client, opts).Extract()
  fmt.Printf("Created network: %v (%v)", network.Name, network.ID)
}
```

The error:
```
$ go run src/github.com/maxlinc/gophercloud-examples/network/create_network.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x393ec]

goroutine 1 [running]:
github.com/rackspace/gophercloud.(*ServiceClient).ServiceURL(0x0, 0x491b28, 0x1, 0x1, 0xc2000e3f60, ...)
	/Users/Thoughtworker/go/src/github.com/rackspace/gophercloud/service_client.go:31 +0x1c
github.com/rackspace/gophercloud/openstack/networking/v2/networks.rootURL(0x0, 0x0, 0x0)
	/Users/Thoughtworker/go/src/github.com/rackspace/gophercloud/openstack/networking/v2/networks/urls.go:10 +0x7b
github.com/rackspace/gophercloud/openstack/networking/v2/networks.createURL(0x0, 0xc200395d00, 0x0)
	/Users/Thoughtworker/go/src/github.com/rackspace/gophercloud/openstack/networking/v2/networks/urls.go:22 +0x25
github.com/rackspace/gophercloud/openstack/networking/v2/networks.Create(0x0, 0xc2000e3ea0, 0xc2000e3ed0, 0x380121, 0x253c30, ...)
	/Users/Thoughtworker/go/src/github.com/rackspace/gophercloud/openstack/networking/v2/networks/requests.go:141 +0xd6
main.main()
	/Users/Thoughtworker/repos/rackspace/polytrix-openstack/sdks/gophercloud/src/github.com/maxlinc/gophercloud-examples/network/create_network.go:31 +0x2a9

goroutine 2 [syscall]:

goroutine 5 [runnable]:
net/http.(*persistConn).readLoop(0xc2000c0180)
	/usr/local/go/src/pkg/net/http/transport.go:761 +0x64b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:511 +0x574

goroutine 6 [select]:
net/http.(*persistConn).writeLoop(0xc2000c0180)
	/usr/local/go/src/pkg/net/http/transport.go:774 +0x26f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:512 +0x58b
exit status 2
```

I thought the value of region might have been the issue, but I've tested with ORD, IAD, DFW and dfw without any luck.

**Comment by jrperritt** [comment]
Rackspace's service name for Networking is "network", not "neutron".

**Comment by jrperritt** [comment]
To be more specific, you're getting that error because you're not checking for an error after you try creating the `NewNetworkV2` client. Checking that error should show you that there isn't an endpoint in the service catalog for the options you provided.

**Comment by maxlinc** [comment]
And it looks like the CreateOpts are different... Thanks!

Related to that I noted in #368 that `NewIdentityV2` looks like it's the only func in the rackspace package that returns a client but cannot return an error. Is that a mistake, does it mean `NewIdentityV2` can never fail, or do you need to use some other technique to check for an error?

**Comment by jrperritt** [comment]
Well, it's not a mistake; we _could_ have had `NewIdentityV2` return an error for consistency, but it would always be `nil`. You can look at the [`NewIdentityV2` function](https://github.com/rackspace/gophercloud/blob/master/rackspace/client.go#L108) and see that there isn't an error to return.
