### ISSUE TITLE
Networking client runtime error when querying for routers

### ISSUE THREAD

**Issue by uruddarraju** [rackspace/gophercloud#423]
The current implementation is throwing a run time error when I do a list on routers and there are no routers present. 

Please refer to the following stack trace:

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xa code=0x2 addr=0x10 pc=0x102740]

goroutine 16 [running]:
runtime.panic(0x2e1900, 0x4f4698)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xc5
github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud.(*ServiceClient).ServiceURL(0x0, 0x113e1a64, 0x1, 0x1, 0x0, 0x0)
	/Users/uruddarraju/gokubeuday/src/github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud/service_client.go:31 +0x30
github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/networking/v2/extensions/layer3/routers.rootURL(0x0, 0x0, 0x0)
	/Users/uruddarraju/gokubeuday/src/github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/networking/v2/extensions/layer3/routers/urls.go:8 +0x70
github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/networking/v2/extensions/layer3/routers.List(0x0, 0x0, 0x0, 0xbffff916, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/uruddarraju/gokubeuday/src/github.com/ebayinc/tessnet/Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go:38 +0xc8 
```

My call:

```go
var routersList []routers.Router
    opts := routers.ListOpts{
        Name: name,
    }
    pager := routers.List(os.nwClient, opts)
```

**Comment by jrperritt** [comment]
It looks you're getting that error because the value of `os.nwClient` is `nil`. Can you post the code where you're setting client?

**Comment by jrperritt** [comment]
Also, here's an example of creating an OpenStack Neutron v2 client in Gophercloud:
https://github.com/rackspace/gophercloud/blob/master/acceptance/openstack/networking/v2/common.go#L14

**Comment by uruddarraju** [comment]
Yeah, I think that is true, had to put in a few print statements to understand that. 

Sorry my bad. Thanks for clarifying it.

**Comment by jrperritt** [comment]
No worries :)
